[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm install && npm run build"  # O il comando di build che usi
  publish = "dist"  # Cartella dove Vite genera l'output di produzione
